
name: Build and Release JAR

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0, v2.1.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew  # Give execute permission to gradlew script

    - name: Build with Gradle
      run: ./gradlew build  # This will build the project and generate the JAR file

    - name: Check Gradle version
      run: ./gradlew --version

    - name: Upload JAR to release
      uses: ncipollo/release-action@v1
      with:
        artifacts: build/libs/*.jar  # Adjust the path to where your JAR is created
        token: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
        tag: ${{ github.ref }}  # Use the Git tag that triggered the release
        release_name: ${{ github.ref }}  # Name the release the same as the tag
        body: "Automated release of JAR file"  # Description for the release
        draft: false
        prerelease: false
